### ISSUE TITLE
Rating test

### ISSUE THREAD

**Issue by kieranoshea7** [debruine/experimentum#3]
This display is fairly small onscreen. Also maybe more explicit instructions - "hit enter once you have typed your rating score"

![screen shot 2018-10-15 at 11 49 11](https://user-images.githubusercontent.com/33661216/46946662-67baa580-d070-11e8-9d65-1c94aff35ec6.png)

![screen shot 2018-10-15 at 11 46 17](https://user-images.githubusercontent.com/33661216/46946596-22967380-d070-11e8-93a8-3a7b3712ba06.png)

**Comment by debruine** [comment]
I removed the rating paradigm entirely (it's terrible on touchscreens)
