### ISSUE TITLE
Slider display 

### ISSUE THREAD

**Issue by RebeccaJLai** [debruine/experimentum#38]
Slider scales don't display the slider element (the purple circle on the second image below) on the scale until clicked on. Minor for sure, but potentially confusing for some.

![image](https://user-images.githubusercontent.com/33028772/58562134-8c8b1400-8220-11e9-94fd-81cdf734805f.png)

![image](https://user-images.githubusercontent.com/33028772/58562160-9c0a5d00-8220-11e9-8c9e-b71df973d6cc.png)

**Comment by debruine** [comment]
This is actually a purposeful feature to avoid the really bad anchoring problems with sliders.
