### ISSUE TITLE
Sorting Test

### ISSUE THREAD

**Issue by kieranoshea7** [debruine/experimentum#4]
1) I'm guessing the text in the screenshot is just supposed to be filler blurb?
2) Perhaps some instructions on how to sort the faces from oldest to youngest? I figured it was top through to bottom and left to right (so oldest on top left and youngest on bottom right) 

![screen shot 2018-10-15 at 11 51 15](https://user-images.githubusercontent.com/33661216/46946860-fe876200-d070-11e8-9df3-17cbefbfcf08.png)

**Comment by debruine** [comment]
Sorry, I'd forgotten a lot of the actual content is filler text. Don't worry about commenting on the actual text of things, just whether you find things intuitive (subjects don't always read the instructions anyways) and if you find any bugs.
