### ISSUE TITLE
Can't open experiments/click reloads page

### ISSUE THREAD

**Issue by JaimieST** [debruine/experimentum#6]
Not sure how to best describe the issue, from the test homepage it can take multiple attempts to open any experiment. sometimes opens on the first click, but can take up to 7/8 attempts before actually opening.

When it does open, anything i try to click on seems to reload the page, so actually doing any of the experiments is impossible.

using Chrome Version 67.0.3396.99 on Mac

**Comment by debruine** [comment]
I just tested it in Chrome 69.0.3497.100 on Mac and can't replicate the problem. Can anyone else replicate the problem?

**Comment by debruine** [comment]
I think moving the login interface to a separate p[age fixed this.
