### ISSUE TITLE
Questionnaire names

### ISSUE THREAD

**Issue by RebeccaJLai** [debruine/experimentum#9]
![image](https://user-images.githubusercontent.com/33028772/47042223-a771b200-d182-11e8-8c25-dd96e52c62ab.png)
![image](https://user-images.githubusercontent.com/33028772/47042244-b5273780-d182-11e8-9ec4-27b077c2bc62.png)
![image](https://user-images.githubusercontent.com/33028772/47042332-ed2e7a80-d182-11e8-9a05-03739cc9b25c.png)

questionnaire name mislabelled at researcher name?

**Comment by debruine** [comment]
I've changed "Researcher Name" to "Name for Researchers". That's not meant to be your name, but a name for the study to display to researchers (often the name displayed to users isn't useful to us).
